### PR TITLE
Images name changed

### LINKED ISSUE #3: Change file names
Convert all file name according to our site

### PR DESCRIPTION
**Pull request by Santhosh1933**
closes #3

### CODE REVIEW

**Review by 0xPugal — APPROVED** [review]

**Review by sanjaydev02 — APPROVED** [review]

**Comment by 0xPugal** [comment]
Looks good! Just noticed that the favicon is missing. Could you please add it?

**Comment by Santhosh1933** [comment]
> Looks good! Just noticed that the favicon is missing. Could you please add it?

Ok 👍

**Comment by Santhosh1933** [comment]
@0xPugal  Typo and favicon Fixed

**Review by 0xPugal — APPROVED** [review]

**Comment by Santhosh1933** [comment]
@0xPugal  Can i merge it

**Pull request merged**
